# Generated by Django 3.0.7 on 2020-06-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("is_done", "-is_priority", "-created_at")},
        ),
    ]
